export type NavbarItem = {
    nav: {
        id: number;
        tablewar: string;
        dilewar: string;
        alewar: string;
        blewar: string;
        clewar: string;
        dlewar: string;
        Golewar: string;
        ablewar: string;
        bbllewar: string;
        cclewar: string;
        ddlewar: string;
        Goolewar: string;
        G1lewar: string;
        G2lewar: string;
        G3lewar: string;
        G4lewar: string;
        G5lewar: string;
        G6lewar: string;
        G7lewar: string;
        G8lewar: string;
        G9lewar: string;
        G10lewar: string;
        G11lewar: string;
        G12lewar: string;
        G13lewar: string;
        G14lewar: string;
        G15lewar: string;
        G16lewar: string;
        G17lewar: string;
        G18lewar: string;
        G19lewar: string;
        G20lewar: string;
        G21lewar: string;
        G22lewar: string;
        G23lewar: string;
        G24lewar: string;
    }[],
}