export interface Country {
    id: string;
    name: string;
  }
  
  export interface City {
    id: string;
    name: string;
  }
  
  export interface Street {
    id: string;
    name: string;
  }
  
  export interface MockData {
    countries: Country[];
    cities: {
      [key: string]: City[];
    };
    streets: {
      [key: string]: Street[];
    };
  }
  
  export const mockData: MockData = {
    countries: [
      { id: '1', name: 'South Korea' },
      { id: '2', name: 'Uzbekistan' },
      { id: '3', name: 'USA' },
      { id: '4', name: 'Germany' },
      { id: '5', name: 'Canada' },
      { id: '6', name: 'Australia' },
      { id: '7', name: 'France' },
      { id: '8', name: 'Russia' },
      { id: '9', name: 'China' },
      { id: '10', name: 'India' }
    ],
    cities: {
      '1': [
        { id: '1', name: 'Seoul' },
        { id: '2', name: 'Busan' },
        { id: '3', name: 'Incheon' },
        { id: '4', name: 'Daegu' },
        { id: '5', name: 'Daejeon' },
        { id: '6', name: 'Gwangju' },
        { id: '7', name: 'Ulsan' },
        { id: '8', name: 'Jeju' },
        { id: '9', name: 'Sejong' },
        { id: '10', name: 'Suwon' },
        { id: '11', name: 'Changwon' },
        { id: '12', name: 'Chuncheon' },
        { id: '13', name: 'Pohang' },
        { id: '14', name: 'Jeonju' },
        { id: '15', name: 'Iksan' },
        { id: '16', name: 'Gimhae' },
        { id: '17', name: 'Goyang' },
        { id: '18', name: 'Hwaseong' },
        { id: '19', name: 'Yangsan' },
        { id: '20', name: 'Pyeongtaek' },
        { id: '21', name: 'Sacheon' },
        { id: '22', name: 'Kimcheon' },
        { id: '23', name: 'Sokcho' },
        { id: '24', name: 'Andong' },
        { id: '25', name: 'Wonju' },
        { id: '26', name: 'Yeosu' },
        { id: '27', name: 'Jinju' },
        { id: '28', name: 'Cheonan' },
        { id: '29', name: 'Gunsan' },
        { id: '30', name: 'Jangseong' },
        { id: '31', name: 'Miryang' },
        { id: '32', name: 'Geumjeong' },
        { id: '33', name: 'Namyangju' },
        { id: '34', name: 'Ansan' },
        { id: '35', name: 'Donghae' },
        { id: '36', name: 'Boryeong' },
        { id: '37', name: 'Cheongju' },
        { id: '38', name: 'Gimpo' },
        { id: '39', name: 'Gwangmyeong' },
        { id: '40', name: 'Jecheon' },
        { id: '41', name: 'Goseong' },
        { id: '42', name: 'Gimje' }
      ],
      '2': [
        { id: '1', name: 'Tashkent' },
        { id: '2', name: 'Samarkand' },
        { id: '3', name: 'Bukhara' },
        { id: '4', name: 'Nukus' },
        { id: '5', name: 'Andijan' },
        { id: '6', name: 'Fergana' },
        { id: '7', name: 'Namangan' },
        { id: '8', name: 'Jizzakh' },
        { id: '9', name: 'Kashkadarya' },
        { id: '10', name: 'Khorezm' },
        { id: '11', name: 'Surxondaryo' },
        { id: '12', name: 'Navoiy' },
        { id: '13', name: 'Bukhara' },
        { id: '14', name: 'Sirdaryo' }
      ],
      '3': [
        { id: '1', name: 'New York' },
        { id: '2', name: 'Los Angeles' },
        { id: '3', name: 'Chicago' },
        { id: '4', name: 'Houston' },
        { id: '5', name: 'Phoenix' },
        { id: '6', name: 'Philadelphia' },
        { id: '7', name: 'San Antonio' },
        { id: '8', name: 'San Diego' },
        { id: '9', name: 'Dallas' },
        { id: '10', name: 'San Jose' },
        { id: '11', name: 'Austin' },
        { id: '12', name: 'Jacksonville' },
        { id: '13', name: 'Fort Worth' },
        { id: '14', name: 'Columbus' },
        { id: '15', name: 'Charlotte' },
        { id: '16', name: 'San Francisco' },
        { id: '17', name: 'Indianapolis' },
        { id: '18', name: 'Seattle' },
        { id: '19', name: 'Denver' },
        { id: '20', name: 'Washington' },
        { id: '21', name: 'Boston' },
        { id: '22', name: 'El Paso' },
        { id: '23', name: 'Detroit' },
        { id: '24', name: 'Nashville' },
        { id: '25', name: 'Portland' },
        { id: '26', name: 'Memphis' },
        { id: '27', name: 'Oklahoma City' },
        { id: '28', name: 'Las Vegas' },
        { id: '29', name: 'Louisville' },
        { id: '30', name: 'Baltimore' },
        { id: '31', name: 'Milwaukee' },
        { id: '32', name: 'Albuquerque' },
        { id: '33', name: 'Tucson' },
        { id: '34', name: 'Fresno' },
        { id: '35', name: 'Sacramento' },
        { id: '36', name: 'Mesa' },
        { id: '37', name: 'Kansas City' },
        { id: '38', name: 'Atlanta' },
        { id: '39', name: 'Long Beach' },
        { id: '40', name: 'Omaha' },
        { id: '41', name: 'Raleigh' },
        { id: '42', name: 'Miami' },
        { id: '43', name: 'Cleveland' },
        { id: '44', name: 'Bakersfield' },
        { id: '45', name: 'Tampa' },
        { id: '46', name: 'St. Louis' },
        { id: '47', name: 'Pittsburgh' },
        { id: '48', name: 'Corpus Christi' },
        { id: '49', name: 'Anchorage' },
        { id: '50', name: 'Lexington' },
        { id: '51', name: 'Stockton' },
        { id: '52', name: 'Cincinnati' },
        { id: '53', name: 'St. Paul' },
        { id: '54', name: 'Toledo' },
        { id: '55', name: 'New Orleans' },
        { id: '56', name: 'Chula Vista' },
        { id: '57', name: 'Jersey City' },
        { id: '58', name: 'Chandler' },
        { id: '59', name: 'Fort Wayne' },
        { id: '60', name: 'Buffalo' },
        { id: '61', name: 'Durham' },
        { id: '62', name: 'Madison' },
        { id: '63', name: 'Lubbock' },
        { id: '64', name: 'Chesapeake' },
        { id: '65', name: 'Gilbert' },
        { id: '66', name: 'Glendale' },
        { id: '67', name: 'Winston-Salem' },
        { id: '68', name: 'North Las Vegas' },
        { id: '69', name: 'Norfolk' },
        { id: '70', name: 'Irvine' },
        { id: '71', name: 'Hartford' },
        { id: '72', name: 'Santa Ana' },
        { id: '73', name: 'Riverside' },
        { id: '74', name: 'Birmingham' },
        { id: '75', name: 'Laredo' },
        { id: '76', name: 'Madison' },
        { id: '77', name: 'Des Moines' },
        { id: '78', name: 'Grand Rapids' },
        { id: '79', name: 'Newport News' },
        { id: '80', name: 'Huntsville' }
      ],
      '4': [
            { id: '1', name: 'Berlin' },
            { id: '2', name: 'Hamburg' },
            { id: '3', name: 'Munich' },
            { id: '4', name: 'Cologne' },
            { id: '5', name: 'Frankfurt' },
            { id: '6', name: 'Stuttgart' },
            { id: '7', name: 'Düsseldorf' },
            { id: '8', name: 'Dortmund' },
            { id: '9', name: 'Essen' },
            { id: '10', name: 'Bremen' },
            { id: '11', name: 'Leipzig' },
            { id: '12', name: 'Dresden' },
            { id: '13', name: 'Hanover' },
            { id: '14', name: 'Nuremberg' },
            { id: '15', name: 'Rostock' },
            { id: '16', name: 'Mannheim' },
            { id: '17', name: 'Aachen' },
            { id: '18', name: 'Bielefeld' },
            { id: '19', name: 'Erfurt' },
            { id: '20', name: 'Chemnitz' },
            { id: '21', name: 'Freiburg' },
            { id: '22', name: 'Wiesbaden' },
            { id: '23', name: 'Karlsruhe' },
            { id: '24', name: 'Mainz' },
            { id: '25', name: 'Saarbrücken' },
            { id: '26', name: 'Oldenburg' },
            { id: '27', name: 'Kiel' },
            { id: '28', name: 'Halle' },
            { id: '29', name: 'Wuppertal' },
            { id: '30', name: 'Göttingen' },
            { id: '31', name: 'Osnabrück' },
            { id: '32', name: 'Münster' },
            { id: '33', name: 'Paderborn' },
            { id: '34', name: 'Regensburg' },
            { id: '35', name: 'Würzburg' },
            { id: '36', name: 'Siegen' },
            { id: '37', name: 'Lübeck' },
            { id: '38', name: 'Trier' },
            { id: '39', name: 'Ludwigshafen' },
            { id: '40', name: 'Remscheid' },
            { id: '41', name: 'Cottbus' },
            { id: '42', name: 'Zwickau' },
            { id: '43', name: 'Jena' },
            { id: '44', name: 'Heilbronn' },
            { id: '45', name: 'Mönchengladbach' },
            { id: '46', name: 'Bochum' },
            { id: '47', name: 'Bottrop' },
            { id: '48', name: 'Augsburg' },
            { id: '49', name: 'Gelsenkirchen' },
            { id: '50', name: 'Hagen' }
      ],
      '5': [
            { id: '1', name: 'Toronto' },
            { id: '2', name: 'Montreal' },
            { id: '3', name: 'Vancouver' },
            { id: '4', name: 'Calgary' },
            { id: '5', name: 'Ottawa' },
            { id: '6', name: 'Edmonton' },
            { id: '7', name: 'Winnipeg' },
            { id: '8', name: 'Quebec City' },
            { id: '9', name: 'Hamilton' },
            { id: '10', name: 'Kitchener' },
            { id: '11', name: 'London' },
            { id: '12', name: 'Victoria' },
            { id: '13', name: 'Halifax' },
            { id: '14', name: 'Oshawa' },
            { id: '15', name: 'Windsor' },
            { id: '16', name: 'Saskatoon' },
            { id: '17', name: "St. John's" },
            { id: '18', name: 'Regina' },
            { id: '19', name: 'Sherbrooke' },
            { id: '20', name: 'Barrie' },
            { id: '21', name: 'Abbotsford' },
            { id: '22', name: 'Kelowna' },
            { id: '23', name: 'Guelph' },
            { id: '24', name: 'Moncton' },
            { id: '25', name: 'Saguenay' },
            { id: '26', name: 'Thunder Bay' },
            { id: '27', name: 'Saint John' },
            { id: '28', name: 'Chicoutimi' },
            { id: '29', name: 'Lethbridge' },
            { id: '30', name: 'Red Deer' },
            { id: '31', name: 'Kamloops' },
            { id: '32', name: 'North Bay' },
            { id: '33', name: 'Peterborough' },
            { id: '34', name: 'Moncton' },
            { id: '35', name: 'Fredericton' },
            { id: '36', name: 'Brockville' },
            { id: '37', name: 'Cornwall' },
            { id: '38', name: 'Sudbury' },
            { id: '39', name: 'Fort McMurray' },
            { id: '40', name: 'Grande Prairie' }
      ],
      '6': [
            { id: '1', name: 'Sydney' },
            { id: '2', name: 'Melbourne' },
            { id: '3', name: 'Brisbane' },
            { id: '4', name: 'Perth' },
            { id: '5', name: 'Adelaide' },
            { id: '6', name: 'Gold Coast' },
            { id: '7', name: 'Canberra' },
            { id: '8', name: 'Newcastle' },
            { id: '9', name: 'Wollongong' },
            { id: '10', name: 'Hobart' },
            { id: '11', name: 'Geelong' },
            { id: '12', name: 'Cairns' },
            { id: '13', name: 'Townsville' },
            { id: '14', name: 'Darwin' },
            { id: '15', name: 'Launceston' },
            { id: '16', name: 'Ballarat' },
            { id: '17', name: 'Bendigo' },
            { id: '18', name: 'Maitland' },
            { id: '19', name: 'Albury' },
            { id: '20', name: 'Melton' },
            { id: '21', name: 'Shepparton' },
            { id: '22', name: 'Sydney Central Coast' },
            { id: '23', name: 'Port Macquarie' },
            { id: '24', name: 'Central Coast' },
            { id: '25', name: 'Mount Isa' },
            { id: '26', name: 'Rockhampton' },
            { id: '27', name: 'Bundaberg' },
            { id: '28', name: 'Nowra' },
            { id: '29', name: 'Batemans Bay' },
            { id: '30', name: 'Sunshine Coast' }
      ],
      '7': [
            { id: '1', name: 'Paris' },
            { id: '2', name: 'Marseille' },
            { id: '3', name: 'Lyon' },
            { id: '4', name: 'Toulouse' },
            { id: '5', name: 'Nice' },
            { id: '6', name: 'Nantes' },
            { id: '7', name: 'Strasbourg' },
            { id: '8', name: 'Montpellier' },
            { id: '9', name: 'Bordeaux' },
            { id: '10', name: 'Lille' },
            { id: '11', name: 'Rennes' },
            { id: '12', name: 'Reims' },
            { id: '13', name: 'Le Havre' },
            { id: '14', name: 'Saint-Étienne' },
            { id: '15', name: 'Toulon' },
            { id: '16', name: 'Angers' },
            { id: '17', name: 'Grenoble' },
            { id: '18', name: 'Dijon' },
            { id: '19', name: 'Le Mans' },
            { id: '20', name: 'Aix-en-Provence' },
            { id: '21', name: 'Brest' },
            { id: '22', name: 'Tours' },
            { id: '23', name: 'Amiens' },
            { id: '24', name: 'Perpignan' },
            { id: '25', name: 'Metz' },
            { id: '26', name: 'Caen' },
            { id: '27', name: 'Mulhouse' },
            { id: '28', name: 'Nancy' },
            { id: '29', name: 'Rouen' },
            { id: '30', name: 'Orléans' }
      ],
      '8': [
            { id: '1', name: 'Moscow' },
            { id: '2', name: 'Saint Petersburg' },
            { id: '3', name: 'Novosibirsk' },
            { id: '4', name: 'Yekaterinburg' },
            { id: '5', name: 'Nizhny Novgorod' },
            { id: '6', name: 'Kazan' },
            { id: '7', name: 'Chelyabinsk' },
            { id: '8', name: 'Omsk' },
            { id: '9', name: 'Samara' },
            { id: '10', name: 'Rostov-on-Don' },
            { id: '11', name: 'Ufa' },
            { id: '12', name: 'Volgograd' },
            { id: '13', name: 'Perm' },
            { id: '14', name: 'Krasnoyarsk' },
            { id: '15', name: 'Voronezh' },
            { id: '16', name: 'Saratov' },
            { id: '17', name: 'Krasnodar' },
            { id: '18', name: 'Tolyatti' },
            { id: '19', name: 'Izhevsk' },
            { id: '20', name: 'Barnaul' },
            { id: '21', name: 'Tyumen' },
            { id: '22', name: 'Makhachkala' },
            { id: '23', name: 'Orenburg' },
            { id: '24', name: 'Kemerovo' },
            { id: '25', name: 'Novokuznetsk' },
            { id: '26', name: 'Surgut' },
            { id: '27', name: 'Yaroslavl' },
            { id: '28', name: 'Kirov' },
            { id: '29', name: 'Vladimir' },
            { id: '30', name: 'Chita' }
      ],
      '9': [
            { id: '1', name: 'Beijing' },
            { id: '2', name: 'Shanghai' },
            { id: '3', name: 'Guangzhou' },
            { id: '4', name: 'Shenzhen' },
            { id: '5', name: 'Chengdu' },
            { id: '6', name: 'Xi\'an' },
            { id: '7', name: 'Hangzhou' },
            { id: '8', name: 'Nanjing' },
            { id: '9', name: 'Wuhan' },
            { id: '10', name: 'Chongqing' },
            { id: '11', name: 'Suzhou' },
            { id: '12', name: 'Tianjin' },
            { id: '13', name: 'Shijiazhuang' },
            { id: '14', name: 'Dalian' },
            { id: '15', name: 'Harbin' },
            { id: '16', name: 'Qingdao' },
            { id: '17', name: 'Zhengzhou' },
            { id: '18', name: 'Xiamen' },
            { id: '19', name: 'Jinan' },
            { id: '20', name: 'Foshan' },
            { id: '21', name: 'Ningbo' },
            { id: '22', name: 'Shenyang' },
            { id: '23', name: 'Kunming' },
            { id: '24', name: 'Lanzhou' },
            { id: '25', name: 'Changsha' },
            { id: '26', name: 'Hefei' },
            { id: '27', name: 'Taiyuan' },
            { id: '28', name: 'Nanchang' },
            { id: '29', name: 'Jilin' },
            { id: '30', name: 'Wuxi' }
      ],
      '10': [
            { id: '1', name: 'New Delhi' },
            { id: '2', name: 'Mumbai' },
            { id: '3', name: 'Bangalore' },
            { id: '4', name: 'Hyderabad' },
            { id: '5', name: 'Ahmedabad' },
            { id: '6', name: 'Chennai' },
            { id: '7', name: 'Kolkata' },
            { id: '8', name: 'Pune' },
            { id: '9', name: 'Jaipur' },
            { id: '10', name: 'Surat' },
            { id: '11', name: 'Lucknow' },
            { id: '12', name: 'Kanpur' },
            { id: '13', name: 'Nagpur' },
            { id: '14', name: 'Indore' },
            { id: '15', name: 'Bhopal' },
            { id: '16', name: 'Visakhapatnam' },
            { id: '17', name: 'Patna' },
            { id: '18', name: 'Vadodara' },
            { id: '19', name: 'Ludhiana' },
            { id: '20', name: 'Coimbatore' },
            { id: '21', name: 'Kochi' },
            { id: '22', name: 'Nashik' },
            { id: '23', name: 'Agra' },
            { id: '24', name: 'Vijayawada' },
            { id: '25', name: 'Meerut' },
            { id: '26', name: 'Madurai' },
            { id: '27', name: 'Guwahati' },
            { id: '28', name: 'Chandigarh' },
            { id: '29', name: 'Mysore' },
            { id: '30', name: 'Noida' }
      ]
    },
    streets: {
      '1': [
        { id: '1', name: 'Gangnam' },
        { id: '2', name: 'Myeongdong' },
        { id: '3', name: 'Insadong' }
      ],
      '2': [
        { id: '1', name: 'Amir Temur' },
        { id: '2', name: 'Samarqand' },
        { id: '3', name: 'Navoi' }
      ],
      '3': [
        { id: '1', name: 'Wall Street' },
        { id: '2', name: 'Fifth Avenue' },
        { id: '3', name: 'Broadway' }
      ],
      '4': [
        { id: '1', name: 'Unter den Linden' },
        { id: '2', name: 'Kurfürstendamm' },
        { id: '3', name: 'Alexanderplatz' }
      ],
      '5': [
        { id: '1', name: 'Yonge Street' },
        { id: '2', name: 'Queen Street' },
        { id: '3', name: 'Bay Street' }
      ],
      '6': [
        { id: '1', name: 'George Street' },
        { id: '2', name: 'Oxford Street' },
        { id: '3', name: 'Collins Street' }
      ],
      '7': [
        { id: '1', name: 'Champs-Élysées' },
        { id: '2', name: 'Rue de Rivoli' },
        { id: '3', name: 'Boulevard Saint-Germain' }
      ],
      '8': [
        { id: '1', name: 'Tverskaya' },
        { id: '2', name: 'Nevsky Prospect' },
        { id: '3', name: 'Arbat Street' }
      ],
      '9': [
        { id: '1', name: 'Wangfujing' },
        { id: '2', name: 'Nanjing Road' },
        { id: '3', name: 'Xintiandi' }
      ],
      '10': [
        { id: '1', name: 'Connaught Place' },
        { id: '2', name: 'Chandni Chowk' },
        { id: '3', name: 'MG Road' }
      ]
    }
  };